"""
Pydantic data models for EQ descriptors.
The final output format must match AIParameterSuggestion::EQBand (AIBrain.h:28-34).
"""

from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field, model_validator


class EQBandSetting(BaseModel):
    """Single parametric EQ band — matches AIBrain.h EQBand struct exactly."""
    frequency: float = Field(..., ge=20.0, le=20000.0, description="Center/corner frequency in Hz")
    gain: float      = Field(..., ge=-24.0, le=24.0,   description="Gain in dB")
    q: float         = Field(..., ge=0.1, le=10.0,     description="Q factor / bandwidth")
    type: int        = Field(..., ge=0, le=4,           description="0=LowCut 1=LowShelf 2=Peak 3=HighShelf 4=HighCut")
    bypass: bool     = Field(default=False)

    def clamp(self) -> "EQBandSetting":
        return EQBandSetting(
            frequency=max(20.0, min(20000.0, self.frequency)),
            gain=max(-24.0, min(24.0, self.gain)),
            q=max(0.1, min(10.0, self.q)),
            type=max(0, min(4, self.type)),
            bypass=self.bypass,
        )


class EQDescriptorEntry(BaseModel):
    """A single semantic descriptor mapped to 8-band Tessera EQ settings."""
    descriptor: str
    bands: list[EQBandSetting] = Field(..., min_length=8, max_length=8)
    source: str                              # "socialfx" | "socialeq" | "augmented"
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    participant_count: int = Field(default=1, ge=1)

    @model_validator(mode="after")
    def check_band_count(self) -> "EQDescriptorEntry":
        if len(self.bands) != 8:
            raise ValueError(f"Expected 8 bands, got {len(self.bands)}")
        return self

    def to_dict(self) -> dict:
        return {
            "descriptor": self.descriptor,
            "bands": [b.model_dump() for b in self.bands],
            "source": self.source,
            "confidence": self.confidence,
            "participant_count": self.participant_count,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "EQDescriptorEntry":
        d = dict(d)
        d["bands"] = [EQBandSetting(**b) for b in d["bands"]]
        return cls(**d)


class TargetCurve(BaseModel):
    """High-resolution 31-band frequency response generated by the LLM (stage 1 output)."""
    explanation: str
    gains: dict[str, float]   # {"20": 2.0, "100": 1.5, ...} — key is str(freq_hz)

    def as_array(self, freqs: list[float]) -> list[float]:
        """Return gain values in order of the given frequency list."""
        return [self.gains.get(str(f), self.gains.get(str(int(f)), 0.0)) for f in freqs]


class EQSuggestion(BaseModel):
    """Final 8-band suggestion returned to the C++ plugin (matches parseSuggestionJson)."""
    explanation: str
    eq: list[EQBandSetting] = Field(..., min_length=8, max_length=8)
    target_curve: Optional[TargetCurve] = Field(default=None, exclude=True)

    def to_plugin_dict(self) -> dict:
        """Serialize to the JSON format expected by AIBrain.h parseSuggestionJson."""
        return {
            "explanation": self.explanation,
            "eq": [b.model_dump(exclude={"bypass": False}) for b in self.eq],
        }
